### ISSUE TITLE
Create API Users Unitary Tests

### ISSUE THREAD

**Issue by jmartinpizarro** [jmartinpizarro/backend-builderplate#5]
Develop basic API Users tests for the backend builderplate. Need to check that the endpoint works correctly, returning the correct headers and/or errors.

- Need to create tests for the **users** route. 
- Need to add more error handlers in the API route (e.g. DELETE user where user cannot be an integer, boolean...

*To Do*

- [ ] Create tests for GET `/get-users`
- [ ] Create tests for POST `/insert-user`
- [ ] Create tests for DELETE `/delete-user`

**Comment by daniell-olaitan** [comment]
Hi there,

I'd love to contribute to this issue!

I have experience in backend development (Flask) and writing tests for API routes, and I’m familiar with error handling for endpoints. Here's how I plan to approach it:

- **Tests for** `GET /get-users`: I'll check for successful data retrieval, response headers, and error handling in cases where no users are found.
- **Tests for** `POST /insert-user`: I’ll validate successful user creation, appropriate status codes, and error handling for invalid inputs (e.g., missing required fields).
- **Tests for** `DELETE /delete-user`: I’ll ensure it correctly deletes a user and includes error handling for invalid user IDs (e.g., ensuring IDs are not integers or booleans).

Let me know if there are any additional requirements or things I should be aware of. I’m looking forward to contributing!

**Comment by jmartinpizarro** [comment]
TY for your support on this project!!

Seems LGTM, create a new branch and get hands on the job!!
