### ISSUE TITLE
Update README - Contributing 

### ISSUE THREAD

**Issue by jmartinpizarro** [jmartinpizarro/backend-builderplate#9]
After the brief description of the contributing content, it is necessary to provide a brief index of how a PR context/Issue should be written (this means having an standard index for all PRs and Issues).

Any interested, please write down how would you approach this.

**Comment by amet407** [comment]
Hi! Could I work on this? I'd add a detailed description of how contributors should write PRs and issues as well as a PR and issue template.

**Comment by jmartinpizarro** [comment]
Sure! Create a branch and continue working with it!

**Comment by kevinDjane** [comment]
Hi new contributor here! I want to follow the idea of amet407, creating a PR template for your repository.
